#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Extract robot name from URDF file.
"""

import argparse
import xml.etree.ElementTree 
import os


def read_robot_name(root):
    """Return the name of the robot specified in the given URDF.
    """
    try:
        name = root.attrib['name']
    except Exception as _:
        name = ''
    
    return name


# Parse an SDF, convert all models to actors, add the gazebo_tf_injector plugin,
# and return it on the command line or write it to an output file.
if __name__ == '__main__': 
    # Parse the command line arguments.
    parser = argparse.ArgumentParser(
        description='Extract robot name from URDF file.') 
    parser.add_argument('input_file')
    args = parser.parse_args()

    # Read the robot name from the URDF file.
    urdf = xml.etree.ElementTree.parse(args.input_file)
    root = urdf.getroot()
    print(read_robot_name(root))
