#!/bin/bash 
# This script takes a URDF file, converts it to SDF, and loads the SDF into
# Gazebo.

# Exit immediately if a command exits with a non-zero status.
set -e

# Check if the URDF was specified.
if [ $# -ne 1 ] 
then
    echo "Please specify exactly one URDF file to convert."
fi

# Read the name of the given URDF from the command line.
urdf=$1

# Determine the folder that contains the robot model.
modelfolder=$(dirname "${urdf}")

# Define variables for bold and normal font.
bf=$(tput bold)
nf=$(tput sgr0)

# Convert the URDF file to SDF.
echo "${bf}Converting ${urdf} to SDF ...${nf}"
gz sdf \
    --print "${urdf}" \
    > "${modelfolder}"/.model.sdf

# Convert the SDF model to an SDF actor.
# By default, robots are converted to SDF models. In order for the robot not to
# be affected by Gazebo's physics engine, it needs to be converted to an actor.
echo "${bf}Converting robot from SDF model to SDF actor ...${nf}"
rosrun gazebo_tf_injector sdf_model_to_actor \
    "${modelfolder}"/.model.sdf \
    "${modelfolder}"/.actor.sdf

# Wait until Gazebo is started up.
echo "${bf}Waiting for Gazebo to be started ..."
while ! rosservice list 2> /dev/null | grep "/gazebo/set_physics_properties" -q 
do
    sleep 0.2
done

# Upload the robot actor to Gazebo.
echo "${bf}Uploading robot SDF to Gazebo ...${nf}"
rosrun gazebo_ros spawn_model \
    -sdf \
    -model robot \
    -file "${modelfolder}"/.actor.sdf

echo "${bf}Done.${nf}"
